/*******************************************************************************
*
* Header file generated by RDP on Apr 28 2026 22:06:46 from demo.bnf
*
*******************************************************************************/
#ifndef DEMO_H
#define DEMO_H

#include "arg.h"
#include "graph.h"
#include "hist.h"
#include "memalloc.h"
#include "scan.h"
#include "set.h"
#include "symbol.h"
#include "textio.h"


/* Maximum number of passes */
#define RDP_PASSES 1

/* Time and date stamp */
#define RDP_STAMP "Generated on Apr 28 2026 22:06:46 and compiled on " __DATE__ " at " __TIME__ 

/* Token enumeration */
enum
{
RDP_TT_BOTTOM = SCAN_P_TOP,
RDP_T_34 /* " */ = SCAN_P_TOP,RDP_T_39 /* ' */,RDP_T_40 /* ( */,RDP_T_41 /* ) */,RDP_T_44 /* , */,RDP_T_46 /* . */,RDP_T_47 /* / */,RDP_T_4742 /* / * */,
RDP_T_4747 /* // */,RDP_T_58 /* : */,RDP_T_59 /* ; */,RDP_T_61 /* = */,RDP_T_64 /* @ */,RDP_T_class,RDP_T_enum,RDP_T_import,
RDP_T_interface,RDP_T_internal,RDP_T_package,RDP_T_private,RDP_T_protected,RDP_T_public,RDP_T_static,RDP_T_typedef,
RDP_T_123 /* { */,RDP_T_125 /* } */,
RDP_TT_TOP
};

/* Tree data types */

typedef struct rdp_tree_node_data_struct
{
  SCAN_DATA
  
} rdp_tree_node_data;
typedef struct rdp_tree_edge_data_struct
{
  int rdp_edge_kind;
  
} rdp_tree_edge_data;

/* Symbol table support */
/* Parser start production */
void CompilationUnit(void);



#endif

/* End of parser.h */
