/*******************************************************************************
*
* Parser generated by RDP on Apr 28 2026 22:06:46 from demo.bnf
*
*******************************************************************************/
#include <time.h>
#include "parser.h"

char
  *rdp_sourcefilename,          /* current source file name */
  **rdp_sourcefilenames,        /* array of source file names */
  *rdp_outputfilename = "demo.out";         /* output file name */

int
  rdp_symbol_echo = 0,                 /* symbol echo flag */
  rdp_verbose = 0,                     /* verbosity flag */
  rdp_sourcefilenumber,                /* Source file counter */
  rdp_pass;                            /* pass number */

int rdp_error_return = 0;              /* return value for main routine */

char *rdp_tokens = "IGNORE\0" 
"ID\0" "INTEGER\0" "REAL\0" "CHAR\0" "CHAR_ESC\0" "STRING\0" "STRING_ESC\0" "COMMENT\0" 
"COMMENT_VISIBLE\0" "COMMENT_NEST\0" "COMMENT_NEST_VISIBLE\0" "COMMENT_LINE\0" "COMMENT_LINE_VISIBLE\0" "EOF\0" "EOLN\0" "'\"'\0" 
"'\''\0" "'('\0" "')'\0" "','\0" "'.'\0" "'/'\0" "'/*'\0" "'//'\0" 
"':'\0" "';'\0" "'='\0" "'@'\0" "'class'\0" "'enum'\0" "'import'\0" "'interface'\0" 
"'internal'\0" "'package'\0" "'private'\0" "'protected'\0" "'public'\0" "'static'\0" "'typedef'\0" "'{'\0" 
"'}'\0" ;


/* Load keywords */
static void rdp_load_keywords(void)
{
  scan_load_keyword("\"", "\\", RDP_T_34 /* " */, SCAN_P_STRING_ESC);
  scan_load_keyword("\'", "\\", RDP_T_39 /* ' */, SCAN_P_STRING_ESC);
  scan_load_keyword("(", NULL, RDP_T_40 /* ( */, SCAN_P_IGNORE);
  scan_load_keyword(")", NULL, RDP_T_41 /* ) */, SCAN_P_IGNORE);
  scan_load_keyword(",", NULL, RDP_T_44 /* , */, SCAN_P_IGNORE);
  scan_load_keyword(".", NULL, RDP_T_46 /* . */, SCAN_P_IGNORE);
  scan_load_keyword("/", NULL, RDP_T_47 /* / */, SCAN_P_IGNORE);
  scan_load_keyword("/*", "*/", RDP_T_4742 /* / * */, SCAN_P_COMMENT_VISIBLE);
  scan_load_keyword("//", NULL, RDP_T_4747 /* // */, SCAN_P_COMMENT_LINE);
  scan_load_keyword(":", NULL, RDP_T_58 /* : */, SCAN_P_IGNORE);
  scan_load_keyword(";", NULL, RDP_T_59 /* ; */, SCAN_P_IGNORE);
  scan_load_keyword("=", NULL, RDP_T_61 /* = */, SCAN_P_IGNORE);
  scan_load_keyword("@", NULL, RDP_T_64 /* @ */, SCAN_P_IGNORE);
  scan_load_keyword("class", NULL, RDP_T_class, SCAN_P_IGNORE);
  scan_load_keyword("enum", NULL, RDP_T_enum, SCAN_P_IGNORE);
  scan_load_keyword("import", NULL, RDP_T_import, SCAN_P_IGNORE);
  scan_load_keyword("interface", NULL, RDP_T_interface, SCAN_P_IGNORE);
  scan_load_keyword("internal", NULL, RDP_T_internal, SCAN_P_IGNORE);
  scan_load_keyword("package", NULL, RDP_T_package, SCAN_P_IGNORE);
  scan_load_keyword("private", NULL, RDP_T_private, SCAN_P_IGNORE);
  scan_load_keyword("protected", NULL, RDP_T_protected, SCAN_P_IGNORE);
  scan_load_keyword("public", NULL, RDP_T_public, SCAN_P_IGNORE);
  scan_load_keyword("static", NULL, RDP_T_static, SCAN_P_IGNORE);
  scan_load_keyword("typedef", NULL, RDP_T_typedef, SCAN_P_IGNORE);
  scan_load_keyword("{", NULL, RDP_T_123 /* { */, SCAN_P_IGNORE);
  scan_load_keyword("}", NULL, RDP_T_125 /* } */, SCAN_P_IGNORE);
}

/* Set declarations */

  set_ AccessModifier_first = SET_NULL;
  set_ AccessModifier_stop = SET_NULL;
  set_ Annotation_stop = SET_NULL;
  set_ Character_stop = SET_NULL;
  set_ Class_stop = SET_NULL;
  set_ CommentLine_stop = SET_NULL;
  set_ CommentNest_stop = SET_NULL;
  set_ CompilationUnit_first = SET_NULL;
  set_ CompilationUnit_stop = SET_NULL;
  set_ Entity_first = SET_NULL;
  set_ Entity_stop = SET_NULL;
  set_ Enum_stop = SET_NULL;
  set_ Import_stop = SET_NULL;
  set_ Interface_stop = SET_NULL;
  set_ InterfaceMethodDeclaration_first = SET_NULL;
  set_ InterfaceMethodDeclaration_stop = SET_NULL;
  set_ MethodOrFieldDeclaration_first = SET_NULL;
  set_ MethodOrFieldDeclaration_stop = SET_NULL;
  set_ PackageDeclaration_stop = SET_NULL;
  set_ Parameters_stop = SET_NULL;
  set_ QualifiedIdentifier_stop = SET_NULL;
  set_ String_stop = SET_NULL;
  set_ Typedef_stop = SET_NULL;
  set_ rdp_Class_4_first = SET_NULL;
  set_ rdp_Class_5_first = SET_NULL;
  set_ rdp_CompilationUnit_4_first = SET_NULL;
  set_ rdp_CompilationUnit_5_first = SET_NULL;
  set_ rdp_CompilationUnit_6_first = SET_NULL;
  set_ rdp_Entity_0_first = SET_NULL;
  set_ rdp_Entity_1_first = SET_NULL;
  set_ rdp_Entity_7_first = SET_NULL;
  set_ rdp_Entity_8_first = SET_NULL;
  set_ rdp_InterfaceMethodDeclaration_0_first = SET_NULL;
  set_ rdp_InterfaceMethodDeclaration_1_first = SET_NULL;
  set_ rdp_InterfaceMethodDeclaration_4_first = SET_NULL;
  set_ rdp_Interface_0_first = SET_NULL;
  set_ rdp_Interface_1_first = SET_NULL;
  set_ rdp_MethodOrFieldDeclaration_0_first = SET_NULL;
  set_ rdp_MethodOrFieldDeclaration_1_first = SET_NULL;
  set_ rdp_MethodOrFieldDeclaration_6_first = SET_NULL;
  set_ rdp_MethodOrFieldDeclaration_7_first = SET_NULL;

/* Initialise sets */

static void rdp_set_initialise(void)
{
  set_assign_list(&AccessModifier_first, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
  set_assign_list(&AccessModifier_stop, SCAN_P_ID, SCAN_P_EOF, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_interface, 
RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, RDP_T_typedef,SET_END);
  set_assign_list(&Annotation_stop, SCAN_P_EOF, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_interface, RDP_T_internal, 
RDP_T_private, RDP_T_protected, RDP_T_public, RDP_T_typedef,SET_END);
  set_assign_list(&Character_stop, SCAN_P_EOF,SET_END);
  set_assign_list(&Class_stop, SCAN_P_EOF, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_interface, RDP_T_internal, 
RDP_T_private, RDP_T_protected, RDP_T_public, RDP_T_typedef,SET_END);
  set_assign_list(&CommentLine_stop, SCAN_P_EOF,SET_END);
  set_assign_list(&CommentNest_stop, SCAN_P_EOF,SET_END);
  set_assign_list(&CompilationUnit_first, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_import, RDP_T_interface, RDP_T_internal, 
RDP_T_package, RDP_T_private, RDP_T_protected, RDP_T_public, RDP_T_typedef, SET_END);
  set_assign_list(&CompilationUnit_stop, SCAN_P_EOF,SET_END);
  set_assign_list(&Entity_first, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_interface, RDP_T_internal, RDP_T_private, 
RDP_T_protected, RDP_T_public, RDP_T_typedef, SET_END);
  set_assign_list(&Entity_stop, SCAN_P_EOF, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_interface, RDP_T_internal, 
RDP_T_private, RDP_T_protected, RDP_T_public, RDP_T_typedef,SET_END);
  set_assign_list(&Enum_stop, SCAN_P_EOF, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_interface, RDP_T_internal, 
RDP_T_private, RDP_T_protected, RDP_T_public, RDP_T_typedef,SET_END);
  set_assign_list(&Import_stop, SCAN_P_EOF, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_import, RDP_T_interface, 
RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, RDP_T_typedef,SET_END);
  set_assign_list(&Interface_stop, SCAN_P_EOF, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_interface, RDP_T_internal, 
RDP_T_private, RDP_T_protected, RDP_T_public, RDP_T_typedef,SET_END);
  set_assign_list(&InterfaceMethodDeclaration_first, SCAN_P_ID, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
  set_assign_list(&InterfaceMethodDeclaration_stop, SCAN_P_ID, SCAN_P_EOF, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, 
RDP_T_125 /* } */,SET_END);
  set_assign_list(&MethodOrFieldDeclaration_first, SCAN_P_ID, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
  set_assign_list(&MethodOrFieldDeclaration_stop, SCAN_P_ID, SCAN_P_EOF, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, 
RDP_T_125 /* } */,SET_END);
  set_assign_list(&PackageDeclaration_stop, SCAN_P_EOF, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_import, RDP_T_interface, 
RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, RDP_T_typedef,SET_END);
  set_assign_list(&Parameters_stop, SCAN_P_EOF, RDP_T_41 /* ) */,SET_END);
  set_assign_list(&QualifiedIdentifier_stop, SCAN_P_EOF, RDP_T_44 /* , */, RDP_T_59 /* ; */, RDP_T_123 /* { */,SET_END);
  set_assign_list(&String_stop, SCAN_P_EOF,SET_END);
  set_assign_list(&Typedef_stop, SCAN_P_EOF, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_interface, RDP_T_internal, 
RDP_T_private, RDP_T_protected, RDP_T_public, RDP_T_typedef,SET_END);
  set_assign_list(&rdp_Class_4_first, SCAN_P_ID, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
  set_assign_list(&rdp_Class_5_first, SCAN_P_ID, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
  set_assign_list(&rdp_CompilationUnit_4_first, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_interface, RDP_T_internal, RDP_T_private, 
RDP_T_protected, RDP_T_public, RDP_T_typedef, SET_END);
  set_assign_list(&rdp_CompilationUnit_5_first, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_interface, RDP_T_internal, RDP_T_private, 
RDP_T_protected, RDP_T_public, RDP_T_typedef, SET_END);
  set_assign_list(&rdp_CompilationUnit_6_first, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_import, RDP_T_interface, RDP_T_internal, 
RDP_T_package, RDP_T_private, RDP_T_protected, RDP_T_public, RDP_T_typedef, SET_END);
  set_assign_list(&rdp_Entity_0_first, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
  set_assign_list(&rdp_Entity_1_first, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
  set_assign_list(&rdp_Entity_7_first, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_interface, RDP_T_typedef, SET_END);
  set_assign_list(&rdp_Entity_8_first, RDP_T_64 /* @ */, RDP_T_class, RDP_T_enum, RDP_T_interface, RDP_T_internal, RDP_T_private, 
RDP_T_protected, RDP_T_public, RDP_T_typedef, SET_END);
  set_assign_list(&rdp_InterfaceMethodDeclaration_0_first, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
  set_assign_list(&rdp_InterfaceMethodDeclaration_1_first, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
  set_assign_list(&rdp_InterfaceMethodDeclaration_4_first, SCAN_P_ID, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
  set_assign_list(&rdp_Interface_0_first, SCAN_P_ID, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
  set_assign_list(&rdp_Interface_1_first, SCAN_P_ID, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
  set_assign_list(&rdp_MethodOrFieldDeclaration_0_first, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
  set_assign_list(&rdp_MethodOrFieldDeclaration_1_first, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
  set_assign_list(&rdp_MethodOrFieldDeclaration_6_first, RDP_T_40 /* ( */, RDP_T_59 /* ; */, SET_END);
  set_assign_list(&rdp_MethodOrFieldDeclaration_7_first, SCAN_P_ID, RDP_T_internal, RDP_T_private, RDP_T_protected, RDP_T_public, SET_END);
}

/* Parser forward declarations and macros */
static void AccessModifier(void);
static void Annotation(void);
static void Class(void);
void CompilationUnit(void);
static void Entity(void);
static void Enum(void);
static void Import(void);
static void Interface(void);
static void InterfaceMethodDeclaration(void);
static void MethodOrFieldDeclaration(void);
static void PackageDeclaration(void);
static void Parameters(void);
static void QualifiedIdentifier(void);
static void Typedef(void);

/* Parser functions */
static void AccessModifier(void)
{
  text_message(TEXT_INFO, "Entered 'AccessModifier'\n");

  {
    if (scan_test("rdp_AccessModifier_0", RDP_T_public, NULL))
    {
      scan_test("AccessModifier", RDP_T_public, &AccessModifier_stop);
      scan_();
    }
    else
    if (scan_test("rdp_AccessModifier_1", RDP_T_internal, NULL))
    {
      scan_test("AccessModifier", RDP_T_internal, &AccessModifier_stop);
      scan_();
    }
    else
    if (scan_test("rdp_AccessModifier_2", RDP_T_protected, NULL))
    {
      scan_test("AccessModifier", RDP_T_protected, &AccessModifier_stop);
      scan_();
    }
    else
    if (scan_test("rdp_AccessModifier_3", RDP_T_private, NULL))
    {
      scan_test("AccessModifier", RDP_T_private, &AccessModifier_stop);
      scan_();
    }
    else
      scan_test_set("AccessModifier", &AccessModifier_first, &AccessModifier_stop)    ;
    scan_test_set("AccessModifier", &AccessModifier_stop, &AccessModifier_stop);
   }
  text_message(TEXT_INFO, "Exited  'AccessModifier'\n");
}

static void Annotation(void)
{
  text_message(TEXT_INFO, "Entered 'Annotation'\n");

  {
    scan_test("Annotation", RDP_T_64 /* @ */, &Annotation_stop);
    scan_();
    scan_test("Annotation", RDP_T_interface, &Annotation_stop);
    scan_();
    scan_test("Annotation", SCAN_P_ID, &Annotation_stop);
    scan_();
    scan_test("Annotation", RDP_T_123 /* { */, &Annotation_stop);
    scan_();
    scan_test("Annotation", RDP_T_125 /* } */, &Annotation_stop);
    scan_();
    scan_test_set("Annotation", &Annotation_stop, &Annotation_stop);
   }
  text_message(TEXT_INFO, "Exited  'Annotation'\n");
}

static void Class(void)
{
  text_message(TEXT_INFO, "Entered 'Class'\n");

  {
    scan_test("Class", RDP_T_class, &Class_stop);
    scan_();
    scan_test("Class", SCAN_P_ID, &Class_stop);
    scan_();
    if (scan_test("rdp_Class_3", RDP_T_58 /* : */, NULL))
    { /* Start of rdp_Class_3 */
      while (1)
      {
        {
          scan_test("Class", RDP_T_58 /* : */, &Class_stop);
          scan_();
          QualifiedIdentifier();
          if (scan_test("rdp_Class_1", RDP_T_44 /* , */, NULL))
          { /* Start of rdp_Class_1 */
            while (1)
            {
              {
                scan_test("Class", RDP_T_44 /* , */, &Class_stop);
                scan_();
                QualifiedIdentifier();
                }
              if (!scan_test("rdp_Class_1", RDP_T_44 /* , */, NULL)) break;
            }
          } /* end of rdp_Class_1 */
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_Class_3 */
    scan_test("Class", RDP_T_123 /* { */, &Class_stop);
    scan_();
    if (scan_test_set("rdp_Class_5", &rdp_Class_5_first, NULL))
    { /* Start of rdp_Class_5 */
      while (1)
      {
        {
          MethodOrFieldDeclaration();
          }
        if (!scan_test_set("rdp_Class_5", &rdp_Class_5_first, NULL)) break;
      }
    } /* end of rdp_Class_5 */
    scan_test("Class", RDP_T_125 /* } */, &Class_stop);
    scan_();
    scan_test_set("Class", &Class_stop, &Class_stop);
   }
  text_message(TEXT_INFO, "Exited  'Class'\n");
}

void CompilationUnit(void)
{
  text_message(TEXT_INFO, "Entered 'CompilationUnit'\n");

  {
    if (scan_test("rdp_CompilationUnit_1", RDP_T_package, NULL))
    { /* Start of rdp_CompilationUnit_1 */
      while (1)
      {
        {
          PackageDeclaration();
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_CompilationUnit_1 */
    if (scan_test("rdp_CompilationUnit_3", RDP_T_import, NULL))
    { /* Start of rdp_CompilationUnit_3 */
      while (1)
      {
        {
          Import();
          }
        if (!scan_test("rdp_CompilationUnit_3", RDP_T_import, NULL)) break;
      }
    } /* end of rdp_CompilationUnit_3 */
    if (scan_test_set("rdp_CompilationUnit_5", &rdp_CompilationUnit_5_first, NULL))
    { /* Start of rdp_CompilationUnit_5 */
      while (1)
      {
        {
          Entity();
          }
        if (!scan_test_set("rdp_CompilationUnit_5", &rdp_CompilationUnit_5_first, NULL)) break;
      }
    } /* end of rdp_CompilationUnit_5 */
    scan_test_set("CompilationUnit", &CompilationUnit_stop, &CompilationUnit_stop);
   }
  text_message(TEXT_INFO, "Exited  'CompilationUnit'\n");
}

static void Entity(void)
{
  text_message(TEXT_INFO, "Entered 'Entity'\n");

  {
    if (scan_test_set("rdp_Entity_1", &rdp_Entity_1_first, NULL))
    { /* Start of rdp_Entity_1 */
      while (1)
      {
        {
          AccessModifier();
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_Entity_1 */
    { /* Start of rdp_Entity_7 */
      while (1)
      {
        scan_test_set("rdp_Entity_7", &rdp_Entity_7_first, &Entity_stop);
        {
          if (scan_test("rdp_Entity_2", RDP_T_class, NULL))
          {
            Class();
          }
          else
          if (scan_test("rdp_Entity_3", RDP_T_interface, NULL))
          {
            Interface();
          }
          else
          if (scan_test("rdp_Entity_4", RDP_T_64 /* @ */, NULL))
          {
            Annotation();
          }
          else
          if (scan_test("rdp_Entity_5", RDP_T_enum, NULL))
          {
            Enum();
          }
          else
          if (scan_test("rdp_Entity_6", RDP_T_typedef, NULL))
          {
            Typedef();
          }
          else
            scan_test_set("rdp_Entity_7", &rdp_Entity_7_first, &Entity_stop)          ;
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_Entity_7 */
    scan_test_set("Entity", &Entity_stop, &Entity_stop);
   }
  text_message(TEXT_INFO, "Exited  'Entity'\n");
}

static void Enum(void)
{
  text_message(TEXT_INFO, "Entered 'Enum'\n");

  {
    scan_test("Enum", RDP_T_enum, &Enum_stop);
    scan_();
    scan_test("Enum", SCAN_P_ID, &Enum_stop);
    scan_();
    scan_test("Enum", RDP_T_123 /* { */, &Enum_stop);
    scan_();
    scan_test("Enum", RDP_T_125 /* } */, &Enum_stop);
    scan_();
    scan_test_set("Enum", &Enum_stop, &Enum_stop);
   }
  text_message(TEXT_INFO, "Exited  'Enum'\n");
}

static void Import(void)
{
  text_message(TEXT_INFO, "Entered 'Import'\n");

  {
    scan_test("Import", RDP_T_import, &Import_stop);
    scan_();
    if (scan_test("rdp_Import_1", RDP_T_static, NULL))
    { /* Start of rdp_Import_1 */
      while (1)
      {
        {
          scan_test("Import", RDP_T_static, &Import_stop);
          scan_();
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_Import_1 */
    scan_test("Import", SCAN_P_ID, &Import_stop);
    scan_();
    if (scan_test("rdp_Import_3", RDP_T_61 /* = */, NULL))
    { /* Start of rdp_Import_3 */
      while (1)
      {
        {
          scan_test("Import", RDP_T_61 /* = */, &Import_stop);
          scan_();
          scan_test("Import", SCAN_P_ID, &Import_stop);
          scan_();
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_Import_3 */
    if (scan_test("rdp_Import_5", RDP_T_46 /* . */, NULL))
    { /* Start of rdp_Import_5 */
      while (1)
      {
        {
          scan_test("Import", RDP_T_46 /* . */, &Import_stop);
          scan_();
          scan_test("Import", SCAN_P_ID, &Import_stop);
          scan_();
          }
        if (!scan_test("rdp_Import_5", RDP_T_46 /* . */, NULL)) break;
      }
    } /* end of rdp_Import_5 */
    scan_test("Import", RDP_T_59 /* ; */, &Import_stop);
    scan_();
    scan_test_set("Import", &Import_stop, &Import_stop);
   }
  text_message(TEXT_INFO, "Exited  'Import'\n");
}

static void Interface(void)
{
  text_message(TEXT_INFO, "Entered 'Interface'\n");

  {
    scan_test("Interface", RDP_T_interface, &Interface_stop);
    scan_();
    scan_test("Interface", SCAN_P_ID, &Interface_stop);
    scan_();
    scan_test("Interface", RDP_T_123 /* { */, &Interface_stop);
    scan_();
    if (scan_test_set("rdp_Interface_1", &rdp_Interface_1_first, NULL))
    { /* Start of rdp_Interface_1 */
      while (1)
      {
        {
          InterfaceMethodDeclaration();
          }
        if (!scan_test_set("rdp_Interface_1", &rdp_Interface_1_first, NULL)) break;
      }
    } /* end of rdp_Interface_1 */
    scan_test("Interface", RDP_T_125 /* } */, &Interface_stop);
    scan_();
    scan_test_set("Interface", &Interface_stop, &Interface_stop);
   }
  text_message(TEXT_INFO, "Exited  'Interface'\n");
}

static void InterfaceMethodDeclaration(void)
{
  text_message(TEXT_INFO, "Entered 'InterfaceMethodDeclaration'\n");

  {
    if (scan_test_set("rdp_InterfaceMethodDeclaration_1", &rdp_InterfaceMethodDeclaration_1_first, NULL))
    { /* Start of rdp_InterfaceMethodDeclaration_1 */
      while (1)
      {
        {
          AccessModifier();
          }
        if (!scan_test_set("rdp_InterfaceMethodDeclaration_1", &rdp_InterfaceMethodDeclaration_1_first, NULL)) break;
      }
    } /* end of rdp_InterfaceMethodDeclaration_1 */
    scan_test("InterfaceMethodDeclaration", SCAN_P_ID, &InterfaceMethodDeclaration_stop);
    scan_();
    scan_test("InterfaceMethodDeclaration", SCAN_P_ID, &InterfaceMethodDeclaration_stop);
    scan_();
    scan_test("InterfaceMethodDeclaration", RDP_T_40 /* ( */, &InterfaceMethodDeclaration_stop);
    scan_();
    if (scan_test("rdp_InterfaceMethodDeclaration_3", SCAN_P_ID, NULL))
    { /* Start of rdp_InterfaceMethodDeclaration_3 */
      while (1)
      {
        {
          Parameters();
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_InterfaceMethodDeclaration_3 */
    scan_test("InterfaceMethodDeclaration", RDP_T_41 /* ) */, &InterfaceMethodDeclaration_stop);
    scan_();
    scan_test("InterfaceMethodDeclaration", RDP_T_59 /* ; */, &InterfaceMethodDeclaration_stop);
    scan_();
    scan_test_set("InterfaceMethodDeclaration", &InterfaceMethodDeclaration_stop, &InterfaceMethodDeclaration_stop);
   }
  text_message(TEXT_INFO, "Exited  'InterfaceMethodDeclaration'\n");
}

static void MethodOrFieldDeclaration(void)
{
  text_message(TEXT_INFO, "Entered 'MethodOrFieldDeclaration'\n");

  {
    if (scan_test_set("rdp_MethodOrFieldDeclaration_1", &rdp_MethodOrFieldDeclaration_1_first, NULL))
    { /* Start of rdp_MethodOrFieldDeclaration_1 */
      while (1)
      {
        {
          AccessModifier();
          }
        if (!scan_test_set("rdp_MethodOrFieldDeclaration_1", &rdp_MethodOrFieldDeclaration_1_first, NULL)) break;
      }
    } /* end of rdp_MethodOrFieldDeclaration_1 */
    scan_test("MethodOrFieldDeclaration", SCAN_P_ID, &MethodOrFieldDeclaration_stop);
    scan_();
    scan_test("MethodOrFieldDeclaration", SCAN_P_ID, &MethodOrFieldDeclaration_stop);
    scan_();
    { /* Start of rdp_MethodOrFieldDeclaration_6 */
      while (1)
      {
        scan_test_set("rdp_MethodOrFieldDeclaration_6", &rdp_MethodOrFieldDeclaration_6_first, &MethodOrFieldDeclaration_stop);
        {
          if (scan_test("rdp_MethodOrFieldDeclaration_4", RDP_T_40 /* ( */, NULL))
          {
            scan_test("MethodOrFieldDeclaration", RDP_T_40 /* ( */, &MethodOrFieldDeclaration_stop);
            scan_();
            if (scan_test("rdp_MethodOrFieldDeclaration_3", SCAN_P_ID, NULL))
            { /* Start of rdp_MethodOrFieldDeclaration_3 */
              while (1)
              {
                {
                  Parameters();
                  }
                break;   /* hi limit is 1! */
              }
            } /* end of rdp_MethodOrFieldDeclaration_3 */
            scan_test("MethodOrFieldDeclaration", RDP_T_41 /* ) */, &MethodOrFieldDeclaration_stop);
            scan_();
            scan_test("MethodOrFieldDeclaration", RDP_T_123 /* { */, &MethodOrFieldDeclaration_stop);
            scan_();
            scan_test("MethodOrFieldDeclaration", RDP_T_125 /* } */, &MethodOrFieldDeclaration_stop);
            scan_();
          }
          else
          if (scan_test("rdp_MethodOrFieldDeclaration_5", RDP_T_59 /* ; */, NULL))
          {
            scan_test("MethodOrFieldDeclaration", RDP_T_59 /* ; */, &MethodOrFieldDeclaration_stop);
            scan_();
          }
          else
            scan_test_set("rdp_MethodOrFieldDeclaration_6", &rdp_MethodOrFieldDeclaration_6_first, &MethodOrFieldDeclaration_stop)          ;
          }
        break;   /* hi limit is 1! */
      }
    } /* end of rdp_MethodOrFieldDeclaration_6 */
    scan_test_set("MethodOrFieldDeclaration", &MethodOrFieldDeclaration_stop, &MethodOrFieldDeclaration_stop);
   }
  text_message(TEXT_INFO, "Exited  'MethodOrFieldDeclaration'\n");
}

static void PackageDeclaration(void)
{
  text_message(TEXT_INFO, "Entered 'PackageDeclaration'\n");

  {
    scan_test("PackageDeclaration", RDP_T_package, &PackageDeclaration_stop);
    scan_();
    QualifiedIdentifier();
    scan_test("PackageDeclaration", RDP_T_59 /* ; */, &PackageDeclaration_stop);
    scan_();
    scan_test_set("PackageDeclaration", &PackageDeclaration_stop, &PackageDeclaration_stop);
   }
  text_message(TEXT_INFO, "Exited  'PackageDeclaration'\n");
}

static void Parameters(void)
{
  text_message(TEXT_INFO, "Entered 'Parameters'\n");

  {
    scan_test("Parameters", SCAN_P_ID, &Parameters_stop);
    scan_();
    scan_test("Parameters", SCAN_P_ID, &Parameters_stop);
    scan_();
    if (scan_test("rdp_Parameters_1", RDP_T_44 /* , */, NULL))
    { /* Start of rdp_Parameters_1 */
      while (1)
      {
        {
          scan_test("Parameters", RDP_T_44 /* , */, &Parameters_stop);
          scan_();
          scan_test("Parameters", SCAN_P_ID, &Parameters_stop);
          scan_();
          scan_test("Parameters", SCAN_P_ID, &Parameters_stop);
          scan_();
          }
        if (!scan_test("rdp_Parameters_1", RDP_T_44 /* , */, NULL)) break;
      }
    } /* end of rdp_Parameters_1 */
    scan_test_set("Parameters", &Parameters_stop, &Parameters_stop);
   }
  text_message(TEXT_INFO, "Exited  'Parameters'\n");
}

static void QualifiedIdentifier(void)
{
  text_message(TEXT_INFO, "Entered 'QualifiedIdentifier'\n");

  {
    scan_test("QualifiedIdentifier", SCAN_P_ID, &QualifiedIdentifier_stop);
    scan_();
    if (scan_test("rdp_QualifiedIdentifier_1", RDP_T_46 /* . */, NULL))
    { /* Start of rdp_QualifiedIdentifier_1 */
      while (1)
      {
        {
          scan_test("QualifiedIdentifier", RDP_T_46 /* . */, &QualifiedIdentifier_stop);
          scan_();
          scan_test("QualifiedIdentifier", SCAN_P_ID, &QualifiedIdentifier_stop);
          scan_();
          }
        if (!scan_test("rdp_QualifiedIdentifier_1", RDP_T_46 /* . */, NULL)) break;
      }
    } /* end of rdp_QualifiedIdentifier_1 */
    scan_test_set("QualifiedIdentifier", &QualifiedIdentifier_stop, &QualifiedIdentifier_stop);
   }
  text_message(TEXT_INFO, "Exited  'QualifiedIdentifier'\n");
}

static void Typedef(void)
{
  text_message(TEXT_INFO, "Entered 'Typedef'\n");

  {
    scan_test("Typedef", RDP_T_typedef, &Typedef_stop);
    scan_();
    scan_test("Typedef", SCAN_P_ID, &Typedef_stop);
    scan_();
    scan_test("Typedef", RDP_T_61 /* = */, &Typedef_stop);
    scan_();
    scan_test("Typedef", SCAN_P_ID, &Typedef_stop);
    scan_();
    scan_test("Typedef", RDP_T_59 /* ; */, &Typedef_stop);
    scan_();
    scan_test_set("Typedef", &Typedef_stop, &Typedef_stop);
   }
  text_message(TEXT_INFO, "Exited  'Typedef'\n");
}

int main(int argc, char *argv[])
{
  clock_t rdp_finish_time, rdp_start_time = clock();
  int
    rdp_symbol_statistics = 0,    /* show symbol_ table statistics flag */
    rdp_line_echo_all = 0,        /* make a listing on all passes flag */
    rdp_filter = 0,               /* filter flag */
    rdp_line_echo = 0,            /* make listing flag */

    rdp_lexicalise = 0;            /* print lexicalised output flag */

  unsigned long rdp_textsize = 35000l;   /* size of scanner text array */

  unsigned long rdp_tabwidth = 8l;   /* tab expansion width */

  char* rdp_vcg_filename = NULL;      /* filename for -V option */

  arg_message("rdparser\n" RDP_STAMP "\n\n""Usage: parser [options] source");

  arg_message("");
  arg_boolean('f', "Filter mode (read from stdin and write to stdout)", &rdp_filter);
  arg_boolean('l', "Make a listing", &rdp_line_echo);
  arg_boolean('L', "Print lexicalised source file", &rdp_lexicalise);
  arg_string ('o', "Write output to filename", &rdp_outputfilename);
  arg_boolean('s', "Echo each scanner symbol as it is read", &rdp_symbol_echo);
  arg_boolean('S', "Print summary symbol table statistics", &rdp_symbol_statistics);
  arg_numeric('t', "Tab expansion width (default 8)", &rdp_tabwidth);
  arg_numeric('T', "Text buffer size in bytes for scanner (default 20000)", &rdp_textsize);
  arg_boolean('v', "Set verbose mode", &rdp_verbose);
  arg_string ('V', "Write derivation tree to filename in VCG format", &rdp_vcg_filename);

  rdp_sourcefilenames = arg_process(argc, argv);

  /* Fix up filetypes */
  for (rdp_sourcefilenumber = 0; rdp_sourcefilenames[rdp_sourcefilenumber] != NULL; rdp_sourcefilenumber++)
    rdp_sourcefilenames[rdp_sourcefilenumber] = text_default_filetype(rdp_sourcefilenames[rdp_sourcefilenumber], "");

  if (rdp_filter)
  {
    rdp_sourcefilenames[0] = "-";
    rdp_outputfilename = "-";
    rdp_sourcefilenames[1] = NULL;     /* make sure no further filenames are taken from the array */

  }
  if ((rdp_sourcefilename = rdp_sourcefilenames[0]) == NULL)
     arg_help("no source files specified");

  if (rdp_sourcefilenames[1] != NULL)
    text_message(TEXT_FATAL, "multiple source files not allowed\n");
  text_init(rdp_textsize, 25, 100, (int) rdp_tabwidth);
  scan_init(0, 0, 0, rdp_symbol_echo, rdp_tokens);
  if (rdp_lexicalise)
    scan_lexicalise();
  rdp_set_initialise();
  rdp_load_keywords();
  if (rdp_verbose)
     text_printf("\nrdparser\n" RDP_STAMP "\n\n");
  for (rdp_pass = 1; rdp_pass <= RDP_PASSES; rdp_pass++)
  {
    text_echo(rdp_line_echo_all || (rdp_line_echo && rdp_pass == RDP_PASSES));

    for (rdp_sourcefilenumber = 0; (rdp_sourcefilename = rdp_sourcefilenames[rdp_sourcefilenumber]) != NULL; rdp_sourcefilenumber++)
    {
      if (text_open(rdp_sourcefilename) == NULL)
        arg_help("unable to open source file");

      text_get_char();
      scan_();

      CompilationUnit();            /* call parser at top level */
      if (text_total_errors() != 0)
        text_message(TEXT_FATAL, "error%s detected in source file 'ðª}è'\n", text_total_errors() == 1 ? "" : "s", rdp_sourcefilename);   /* crash quietly */ 
    }
  }

  rdp_sourcefilename = rdp_sourcefilenames[0];     /* Reset filename to first file in the list */

  if (rdp_symbol_statistics)
  {
    symbol_print_all_table_statistics(11);
    symbol_print_all_table();

  }
  text_print_total_errors();
  if (rdp_verbose)
  {
    rdp_finish_time = clock();
    text_message(TEXT_INFO, "%.3f CPU seconds used\n", ((double) (rdp_finish_time-rdp_start_time)) / CLOCKS_PER_SEC);
  }
  return rdp_error_return;
}

/* End of parser.c */
